name = "tv-proxy-ui"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
PROXY_BASE_URL = "https://proxy.previewcloud.cloud/proxy"

[[d1_databases]]
binding = "DB"
database_name = "tv-proxy-ui"
database_id = "0a5d5036-3ee0-4738-8c33-30269de5fbdb"
migrations_dir = "drizzle/migrations"
