name = "tv-proxy-ui"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
PROXY_BASE_URL = "https://proxy.previewcloud.cloud/proxy"
